mod common_subexpression_elimination;
mod sparse_conditional_constant_prop;
mod constant_folding;
mod const_prop;
mod copy_prop;
mod dce;
pub use sparse_conditional_constant_prop::SparseConditionalConstantProp;
pub use common_subexpression_elimination::CommonSubexpressionElimination;
pub use constant_folding::ConstantFolding;
pub use const_prop::ConstantPropagation;
pub use copy_prop::CopyPropagation;
pub use dce::DeadCodeElim;